# Generated by Django 3.1.4 on 2021-01-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIIApp', '0003_auto_20210118_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='nombre',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.TextField(null=True, verbose_name='Duración'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.DateField(null=True, verbose_name='Fecha estreno'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='generos',
            field=models.ManyToManyField(to='AIIApp.Genero'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='puntuacion',
            field=models.IntegerField(null=True, verbose_name='Puntuacion'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='resumen',
            field=models.TextField(null=True, verbose_name='Resumen'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='titulo',
            field=models.TextField(null=True, verbose_name='Titulo'),
        ),
    ]
