# Generated by Django 3.1.4 on 2021-01-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIIApp', '0004_auto_20210119_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='puntuacion',
        ),
    ]
